# Generated by Django 5.2.8 on 2026-06-25 19:49

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_auditlog_if_absent(apps: Any, schema_editor: Any) -> None:
    """Create the AuditLog table only if it does not already exist.

    Earlier releases of ``observe_kit.audit`` shipped without migrations, so an
    existing deployment may already have the table (created via
    ``migrate --run-syncdb`` or a manual ``schema_editor.create_model``). This
    initial migration adopts that table instead of aborting the deploy with a
    "table already exists" error. New databases still get the table created
    normally.

    The model is fetched from the migration's historical state (via ``apps``),
    not imported from ``observe_kit.audit.models`` — so this stays a faithful
    snapshot of the 0001 schema even as the live model evolves.
    """
    AuditLog = apps.get_model("audit", "AuditLog")
    if AuditLog._meta.db_table in schema_editor.connection.introspection.table_names():
        return
    schema_editor.create_model(AuditLog)


def _drop_auditlog_if_present(apps: Any, schema_editor: Any) -> None:
    AuditLog = apps.get_model("audit", "AuditLog")
    if AuditLog._meta.db_table not in schema_editor.connection.introspection.table_names():
        return
    schema_editor.delete_model(AuditLog)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Register AuditLog in migration *state* only (no database changes here),
        # so both makemigrations and the RunPython below see the historical
        # model without importing the live one.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('action', models.CharField(max_length=128)),
                        ('object_type', models.CharField(blank=True, max_length=128, null=True)),
                        ('object_id', models.CharField(blank=True, max_length=256, null=True)),
                        ('tenant_id', models.CharField(blank=True, max_length=128, null=True)),
                        ('trace_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                        ('remote_addr', models.CharField(blank=True, max_length=64, null=True)),
                        ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                        ('extra', models.JSONField(blank=True, default=dict)),
                        ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-timestamp'],
                    },
                ),
            ],
            database_operations=[],
        ),
        # Idempotent DB creation: the state already knows AuditLog, so
        # apps.get_model returns the historical model. Creates the table only
        # when absent (adopting a table left over from the pre-migration era);
        # reverse drops it since this app owns the table.
        migrations.RunPython(_create_auditlog_if_absent, _drop_auditlog_if_present),
    ]
