# Generated by Django 5.2.8 on 2026-06-25 19:49

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_auditlog_if_absent(apps: Any, schema_editor: Any) -> None:
    """Create the AuditLog table only if it does not already exist.

    Earlier releases of ``observe_kit.audit`` shipped without migrations, so an
    existing deployment may already have the table (created via
    ``migrate --run-syncdb`` or a manual ``schema_editor.create_model``). This
    initial migration adopts that table instead of aborting the deploy with a
    "table already exists" error. New databases still get the table created
    normally.

    The model isn't in the historical ``apps`` state at this point (the
    ``CreateModel`` lives in ``state_operations``), so import the concrete
    model — it matches the state definition exactly for table creation.
    """
    from observe_kit.audit.models import AuditLog

    if AuditLog._meta.db_table in schema_editor.connection.introspection.table_names():
        return
    schema_editor.create_model(AuditLog)


def _drop_auditlog_if_present(apps: Any, schema_editor: Any) -> None:
    from observe_kit.audit.models import AuditLog

    if AuditLog._meta.db_table not in schema_editor.connection.introspection.table_names():
        return
    schema_editor.delete_model(AuditLog)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Keep the CreateModel in migration *state* (so makemigrations and later
        # migrations see the correct model), but make the actual *database*
        # creation idempotent so this first-ever migration can adopt a table
        # left over from the previous no-migrations version of the app.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('action', models.CharField(max_length=128)),
                        ('object_type', models.CharField(blank=True, max_length=128, null=True)),
                        ('object_id', models.CharField(blank=True, max_length=256, null=True)),
                        ('tenant_id', models.CharField(blank=True, max_length=128, null=True)),
                        ('trace_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                        ('remote_addr', models.CharField(blank=True, max_length=64, null=True)),
                        ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                        ('extra', models.JSONField(blank=True, default=dict)),
                        ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-timestamp'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_create_auditlog_if_absent, _drop_auditlog_if_present),
            ],
        ),
    ]
